Repository hometown-fork/hometown, pull requests merged in 2020-07, with the labels that each got.

#66 add server list wiki link
  README.md
Labels: documentation, enhancement

#65 explain why the fork is needed
  README.md
Labels: documentation, enhancement

#56 use the hometown logo on public pages
  app/helpers/accounts_helper.rb
  app/views/layouts/application.html.haml
Labels: bug

#40 Add max_toot_chars patch from glitch-soc
  .env.production.sample
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
  app/serializers/rest/instance_serializer.rb
  app/validators/status_length_validator.rb
Labels: enhancement
